In [2]:
### Build custom layers

# TensorFlow provides both a set of many common layers as a well as easy ways for you to write
# your own application-specific layers either from scratch or as the composition of existing layers.

# It is recommanded to use tf.keras to build a NN. (TensorFlow includes the full Keras API in the tf.keras package)
# But let's understand how to create a layer in more detail

In [3]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

tf.enable_eager_execution()

W0903 11:13:06.097899 140735803462528 __init__.py:690] 

  TensorFlow's `tf-nightly` package will soon be updated to TensorFlow 2.0.

  Please upgrade your code to TensorFlow 2.0:
    * https://www.tensorflow.org/beta/guide/migration_guide

  Or install the latest stable TensorFlow 1.X release:
    * `pip install -U "tensorflow==1.*"`

  Otherwise your code may be broken by the change.

  


In [4]:
# Example of how to create a layer with keras

# Most layers take as a first argument the number of output dimensions / channels.
layer = tf.keras.layers.Dense(100)

# # The number of input dimensions is often unnecessary, as it can be inferred
# the first time the layer is used, but it can be provided if you want to
# specify it manually, which is useful in some complex models. 
# It is necessary to mention it to use the model.summary() method
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

# None means this dimension is variable.
# The first dimension in a keras model is always the batch size.

# To use a layer, simply call it. Specify the input as argument

layer(tf.zeros((10, 5))) # shape is 10 x 10 (batch size x number of hidden units)

<tf.Tensor: id=29, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [5]:
# Layers have many useful methods. For example, you can inspect all variables
# in a layer using layer.variables and trainable variables using
# layer.trainable_variables. In this case a fully-connected layer
# will have variables for weights and biases.
layer.variables # W (10 x 5) and b (10 x 1)

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.44145542, -0.5323926 , -0.104366  ,  0.19480467,  0.1309818 ,
          0.24342811,  0.2775995 ,  0.37767726, -0.23948544, -0.5483116 ],
        [ 0.19261807,  0.5645605 , -0.00918198, -0.09430081, -0.16263017,
          0.3170185 , -0.27144808,  0.26175082,  0.24306595,  0.14648199],
        [-0.58918357, -0.3689554 ,  0.16178197,  0.40211958, -0.6148025 ,
          0.5537335 ,  0.5508148 ,  0.60364324, -0.35310385,  0.5201954 ],
        [-0.4334734 , -0.38740355,  0.23373508, -0.39353704, -0.5196559 ,
         -0.6318864 ,  0.39657396,  0.13487875, -0.56456244,  0.59374934],
        [-0.48353451,  0.16812855, -0.43188772,  0.2932359 , -0.2356584 ,
          0.28270495, -0.04375225,  0.4093544 , -0.28553525, -0.23817027]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [6]:
# The variables are also accessible through nice accessors
layer.kernel, layer.bias # kernel reference to W and bias to b

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.44145542, -0.5323926 , -0.104366  ,  0.19480467,  0.1309818 ,
          0.24342811,  0.2775995 ,  0.37767726, -0.23948544, -0.5483116 ],
        [ 0.19261807,  0.5645605 , -0.00918198, -0.09430081, -0.16263017,
          0.3170185 , -0.27144808,  0.26175082,  0.24306595,  0.14648199],
        [-0.58918357, -0.3689554 ,  0.16178197,  0.40211958, -0.6148025 ,
          0.5537335 ,  0.5508148 ,  0.60364324, -0.35310385,  0.5201954 ],
        [-0.4334734 , -0.38740355,  0.23373508, -0.39353704, -0.5196559 ,
         -0.6318864 ,  0.39657396,  0.13487875, -0.56456244,  0.59374934],
        [-0.48353451,  0.16812855, -0.43188772,  0.2932359 , -0.2356584 ,
          0.28270495, -0.04375225,  0.4093544 , -0.28553525, -0.23817027]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [7]:
### Implementing custom layer

# Create a layer by inheriting from tf.keras.layers.Layers

class myDenseLayer(tf.keras.layers.Layer):
    '''  Define a custom layer
    '''
    
    def __init__(self, num_outputs):
        '''  Do all input-independent initialization
        '''
        super(myDenseLayer, self).__init__() # Pass no argument to the parent class
        self.num_outputs = num_outputs
        
    def build(self, input_shape):
        ''' Do the rest of the initialization since you know the shape of the input
            input_shape          Shape of the input (TensorShape)
        '''
        # Add weight to the model (Adds a new variable to the layer.)
        self.kernel = self.add_variable('kernel', # name
                                         shape=[input_shape[-1], # number of features
                                                self.num_outputs]) # number of hidden units
    def call(self, input):
        ''' Do forward propagation
            input          Tensor
        '''
        return tf.matmul(input, self.kernel) # (m x n) * (n x num_ouputs) -> (m x num_outputs)
    
# Initialize and test our custom layer
layer = myDenseLayer(10)
print('Forward propagation of the customer layer : \n', layer(tf.zeros((10, 5))))
print('\n\nTrainable parameters: ', layer.trainable_variables)


W0903 11:13:06.275596 140735803462528 deprecation.py:323] From <ipython-input-7-ee93dd541baf>:22: Layer.add_variable (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.


Forward propagation of the customer layer : 
 tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)


Trainable parameters:  [<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.3174814 , -0.34096202,  0.60105854,  0.24612862, -0.33708492,
         0.49505514, -0.16772625,  0.43777126, -0.2138356 ,  0.537986  ],
       [-0.52330047, -0.16212142, -0.17449832,  0.19706953, -0.5946049 ,
        -0.29093936,  0.02717417,  0.4796396 , -0.44050065,  0.20151687],
       [ 0.34372354, -0.57321155, -0.17838523, -0.54831445, -0.2651137 ,
        -0.6297469 , -0.00578636, -0.44437638,  0.43090492, -0.13636315],
       [-0.51094544,  0.30369794,  0.5

In [9]:
### Composing layers

# To create a layer which combine several layers, inherit from keras.Model
# Let's build a ResNet layer

class ResNet_layer(tf.keras.Model):
    ''' Construct a ResNet layer: 
        X is fed to (CONV -> BatchNorm -> ReLu) (x2) -> CONV -> BatchNorm -> + X -> Relu
        ('Skip connection' over 2 layers)
        The shape of the filters in the first and last convolution is (1 x 1)
    '''
    
    def __init__(self, kernel_size, filters):
        ''' Do all input-independent initialization
            
            kernel_size      size of the filter for the second convolution
            filters          the number of filters in the convolution (list of integer)
        '''
        super(ResNet_layer, self).__init__(name = '')
        filter_1, filter_2, filter_3 = filters # Unpack the number of filters in each convolution
        
        # First layer
        self.conv_1 = tf.keras.layers.Conv2D(filter_1, (1, 1))
        self.bn_1 = tf.keras.layers.BatchNormalization()
        
        # Second layer
        self.conv_2 = tf.keras.layers.Conv2D(filter_2, kernel_size, padding = 'same')
        self.bn_2 = tf.keras.layers.BatchNormalization()
        
        # Third layer
        self.conv_3 = tf.keras.layers.Conv2D(filter_3, (1, 1))
        self.bn_3 = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training = False):
        ''' Given the input, perform a forward-propagation step
            
            training    Whether to return the output in training mode (normalized with statistics of the current batch)
                        or in inference mode (normalized with moving statistics)
        '''
        
        # First layer
        X = self.conv_1(input_tensor)
        X = self.bn_1(X, training = training) 
        X = tf.nn.relu(X)
        
        # Second layer
        X = self.conv_2(input_tensor)
        X = self.bn_2(X, training = training)
        X = tf.nn.relu(X)
        
        # Third layer
        X = self.conv_3(input_tensor)
        X = self.bn_3(X, training = training)
        # Add the input ('Skip connection' link)
        X = X + input_tensor
        X = tf.nn.relu(X)
        
        return X
    
# Create a ResNet layer
layer = ResNet_layer(1, [1, 2, 3])
# Perform forward propagation 
print(layer(tf.zeros((1, 2, 3, 3))))
# Print each parameters
print([var.name for var in layer.trainable_variables])
        
        
        

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['res_net_layer_1/conv2d_2/kernel:0', 'res_net_layer_1/conv2d_2/bias:0', 'res_net_layer_1/batch_normalization_2/gamma:0', 'res_net_layer_1/batch_normalization_2/beta:0', 'res_net_layer_1/conv2d_3/kernel:0', 'res_net_layer_1/conv2d_3/bias:0', 'res_net_layer_1/batch_normalization_3/gamma:0', 'res_net_layer_1/batch_normalization_3/beta:0', 'res_net_layer_1/conv2d_4/kernel:0', 'res_net_layer_1/conv2d_4/bias:0', 'res_net_layer_1/batch_normalization_4/gamma:0', 'res_net_layer_1/batch_normalization_4/beta:0']


In [11]:
# Much of the time, however, models which compose many layers simply call one layer after the other.
# This can be done in very little code using tf.keras.Sequential

customer_layer = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1)),
                                     tf.keras.layers.BatchNormalization(), # No ReLU ?
                                     tf.keras.layers.Conv2D(2, (1, 1), padding = 'same'),
                                     tf.keras.layers.BatchNormalization(),
                                     tf.keras.layers.Conv2D(3, (1, 1)),
                                     tf.keras.layers.BatchNormalization()])

customer_layer(tf.zeros((1, 2, 3, 3))) # 1 training example, n_h = 2, n_w = 3, n_c = 3

<tf.Tensor: id=505, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>